version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password # 设置 root 密码
      MYSQL_DATABASE: disfinder # 创建名为 disfinder 的数据库
      MYSQL_USER: disfinder # 创建一个名为 disfinder 的普通用户
      MYSQL_PASSWORD: disfinder_passwd # 设置该用户的密码
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./backend # 指定 Go 后端目录
    depends_on:
      - mysql
    ports:
      - "8081:8080"

  frontend:
    build:
      context: ./frontend # 指定 Next.js 前端目录
    depends_on:
      - backend
    ports:
      - "3010:3000"

  scraper:
    build:
      context: ./scraper # 指定 Python 爬虫目录
    depends_on:
      - backend
    command: [ "python", "server.py" ]
    ports:
      - "8002:8888"

volumes:
  mysql-data:
