App:
  RunLevel: debug
#  RunLevel: release

WebServer:
  Port: 8080
  WriteTimeout: 10 #ms
  ReadTimeout: 10 #ms

Database:
  DSN: username:pwd@tcp(host:port)/database?charset=utf8mb4&parseTime=True&loc=Local
Database_test:
  DSN: username:pwd@tcp(host:port)/database?charset=utf8mb4&parseTime=True&loc=Local

Auth:
  Secret: "sDxKfryE9s3FZWq7kjJl"

Service:
  PollingInterval: 1 #hour

Email:
  Host: smtp.gmail.com
  Port: 587
  User: example.gmail.com
  Password: password